alias: EG4 Battery Grid Export Management
description: Manage battery charging when grid export exceeds 14kW
mode: single

trigger:
  - platform: numeric_state
    entity_id: sensor.grid_power
    below: -14000  # Negative value indicates export (14kW threshold)
    for:
      seconds: 30  # Avoid triggering on brief spikes

condition:
  - condition: time
    before: "16:00:00"  # Only run before 4:00 PM
  - condition: numeric_state
    entity_id: number.18kpv_1234567890_system_charge_soc_limit
    below: 100  # Only run if not already set to 100%

action:
  # Step 1: Set charge SOC limit to 100%
  - service: number.set_value
    data:
      value: 100
    target:
      entity_id: number.18kpv_1234567890_system_charge_soc_limit
  
  # Step 2: Calculate optimal charge rate
  - variables:
      battery_capacity_kwh: 42.9  # 14.3kWh × 3 batteries
      battery_capacity_wh: 42900  # Total capacity in watt-hours
      # Get current SOC
      current_soc: >
        {{ states('sensor.18kpv_1234567890_state_of_charge') | float(50) }}
      # Calculate energy needed to reach 100%
      energy_needed_wh: >
        {{ (battery_capacity_wh | float * ((100 - current_soc | float) / 100)) | float }}
      # Calculate hours until 4:00 PM
      current_time: >
        {{ now() }}
      target_time: >
        {{ today_at('16:00') }}
      hours_remaining: >
        {{ ((target_time | as_timestamp - current_time | as_timestamp) / 3600) | float(1) }}
      # Calculate required charge rate in kW (with safety margin)
      required_charge_rate_kw: >
        {{ ((energy_needed_wh | float / 1000) / hours_remaining | float * 1.1) | float(1) }}
      # Apply min/max limits in kW
      min_charge_rate_kw: 1  # Minimum 1kW as integer
      max_charge_rate_kw: 12  # Maximum 12kW for 3-battery system
      final_charge_rate_kw: >
        {{ ([max_charge_rate_kw | float, [min_charge_rate_kw | float, required_charge_rate_kw | float] | max] | min) | round(0, 'ceil') | int }}
  
  # Step 3: Set the calculated charge rate
  - service: number.set_value
    data:
      value: "{{ final_charge_rate_kw | int }}"
    target:
      entity_id: number.18kpv_1234567890_pv_charge_power
  
  # Step 4: Send notification (optional)
  - service: notify.persistent_notification
    data:
      title: "EG4 Battery Charging Adjusted"
      message: >
        Grid export exceeded 14kW.
        Current SOC: {{ current_soc | float }}%
        Time until 4 PM: {{ hours_remaining | float | round(1) }} hours
        Charge rate set to: {{ final_charge_rate_kw | int }}kW
        Energy needed: {{ (energy_needed_wh | float / 1000) | round(2) }}kWh