// Force-create functions at specific addresses and decompile them.
// These are mid-function labels that Ghidra's auto-analysis missed.
//@category Analysis

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.SourceType;

import java.io.*;

public class GhidraForceDecompile extends GhidraScript {

    // Addresses that Ghidra couldn't decompile as standalone functions.
    // These are jump labels within rs485_service_task (0x4200c4cc).
    private static final String[][] TARGETS = {
        // The RS485 data ready callback - fires when inverter responds to register read.
        // This is the CRITICAL function that builds the cloud 0xC2 frame from Modbus response.
        {"4200aaec", "RS485_DataReadyCallback", "400"},

        // Status register callback - fires for status register reads.
        {"4200aa4a", "RS485_StatusCallback", "160"},

        // The RS485 service task entry point itself.
        {"4200c4cc", "rs485_service_task", "1500"},

        // Also try the surrounding code to capture the full callback dispatch logic.
        {"4200a9d0", "RS485_CallbackDispatch", "300"},

        // DataProcess_ResponseBuilder - builds response frame to send back to cloud
        {"4200c260", "DataProcess_ResponseBuilder", "100"},
    };

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String outputPath = args.length > 0 ? args[0]
            : "/tmp/ghidra_esp32_output/decompiled_force.c";
        new File(outputPath).getParentFile().mkdirs();

        DecompInterface decomp = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        decomp.setOptions(opts);
        decomp.openProgram(currentProgram);

        FunctionManager funcMgr = currentProgram.getFunctionManager();
        AddressSpace space = currentProgram.getAddressFactory().getDefaultAddressSpace();
        Listing listing = currentProgram.getListing();

        int count = 0;

        try (PrintWriter pw = new PrintWriter(new FileWriter(outputPath))) {
            pw.println("// Force-decompiled functions at addresses Ghidra missed.");
            pw.println("// These are mid-function labels within rs485_service_task.");
            pw.println("// Generated by GhidraForceDecompile.java");
            pw.println();

            for (String[] target : TARGETS) {
                String addrStr = target[0];
                String name = target[1];
                int size = Integer.parseInt(target[2]);
                Address addr = space.getAddress(Long.parseUnsignedLong(addrStr, 16));

                println("--- Processing 0x" + addrStr + " (" + name + ") ---");

                // Step 1: Check if function already exists at this address
                Function func = funcMgr.getFunctionAt(addr);
                if (func != null) {
                    println("  Function already exists: " + func.getName());
                } else {
                    // Step 2: Check if this address is inside another function
                    Function containing = funcMgr.getFunctionContaining(addr);
                    if (containing != null) {
                        println("  Address is inside " + containing.getName()
                            + " @ " + containing.getEntryPoint());
                        println("  Attempting to split/create function anyway...");

                        // Try to remove the containing function's claim on this range
                        // and create a new function
                        try {
                            // Create function body from addr to addr+size
                            AddressSet body = new AddressSet(addr, addr.add(size - 1));
                            func = funcMgr.createFunction(
                                name, addr, body, SourceType.USER_DEFINED);
                            println("  Created function: " + func.getName());
                        } catch (Exception e) {
                            println("  Split failed: " + e.getMessage());
                            // Fall back: just decompile the containing function
                            func = containing;
                            println("  Falling back to containing function: "
                                + func.getName());
                        }
                    } else {
                        // Step 3: No function here at all - create one
                        println("  No function found, creating...");
                        try {
                            AddressSet body = new AddressSet(addr, addr.add(size - 1));
                            func = funcMgr.createFunction(
                                name, addr, body, SourceType.USER_DEFINED);
                            println("  Created function: " + func.getName());
                        } catch (Exception e) {
                            println("  Create failed: " + e.getMessage());
                            // Try with disassembly first
                            try {
                                disassemble(addr);
                                func = createFunction(addr, name);
                                if (func != null) {
                                    println("  Created after disassembly: " + func.getName());
                                }
                            } catch (Exception e2) {
                                println("  Disassemble+create also failed: " + e2.getMessage());
                            }
                        }
                    }
                }

                if (func == null) {
                    pw.printf("// === 0x%s: %s === (could not create function)%n%n",
                        addrStr, name);
                    continue;
                }

                // Step 4: Decompile
                DecompileResults result = decomp.decompileFunction(func, 120, monitor);
                if (result != null && result.getDecompiledFunction() != null) {
                    String code = result.getDecompiledFunction().getC();
                    if (code != null && !code.isEmpty()) {
                        pw.printf("// === 0x%s: %s ===%n", addrStr, name);
                        pw.printf("// Function: %s @ %s (%d bytes)%n%n",
                            func.getName(), func.getEntryPoint(),
                            func.getBody().getNumAddresses());
                        pw.println(code);
                        pw.println();
                        pw.println("=" .repeat(80));
                        pw.println();
                        count++;
                        println("  Decompiled OK (" + func.getBody().getNumAddresses()
                            + " bytes)");
                    } else {
                        pw.printf("// === 0x%s: %s === (empty decompilation)%n%n",
                            addrStr, name);
                        println("  Decompilation produced empty output");
                    }
                } else {
                    pw.printf("// === 0x%s: %s === (decompilation failed)%n%n",
                        addrStr, name);
                    String errMsg = result != null ? result.getErrorMessage() : "null result";
                    println("  Decompilation failed: " + errMsg);
                }

                // Step 5: Also dump raw disassembly for context
                pw.printf("// --- Raw disassembly at 0x%s (first 60 instructions) ---%n",
                    addrStr);
                InstructionIterator instrIter = listing.getInstructions(addr, true);
                int instrCount = 0;
                while (instrIter.hasNext() && instrCount < 60) {
                    Instruction instr = instrIter.next();
                    pw.printf("//   %s: %s  %s%n",
                        instr.getAddress(), instr.getMnemonicString(), instr.toString());
                    instrCount++;
                    // Stop if we hit a return instruction
                    if (instr.getMnemonicString().startsWith("ret") && instrCount > 5) {
                        break;
                    }
                }
                pw.println();
                pw.println("=" .repeat(80));
                pw.println();
            }

            pw.printf("%n// Total: %d/%d functions decompiled%n", count, TARGETS.length);
        }

        decomp.dispose();
        println("\nOutput: " + outputPath);
        println("Decompiled " + count + "/" + TARGETS.length + " functions");
    }
}
