// Decompile functions missing from the original targeted analysis.
//@category Analysis

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.listing.*;

import java.io.*;

public class GhidraDecompileMissing extends GhidraScript {

    // Functions missing from decompiled_targeted.c
    private static final String[][] TARGETS = {
        // SET_PARAM response builder (ACK frame) — 96 bytes
        {"4200c2e2", "SetParam_ResponseBuilder (build SET_PARAM ACK/NACK response)"},

        // TCP recv callback wrapper — 30 bytes
        {"4200a66a", "TCPClient_RecvCallback (recv callback wrapper for frame parsing)"},

        // DataProcess frame parser (used by BLE, likely also TCP path) — 426 bytes
        {"42009c16", "DataProcess_FrameParser (parse 0xA1/0x1A frames from stream)"},

        // TCP client main loop — 1182 bytes (already in decompiled_protocol.c but add here for completeness)
        {"4200d67c", "TCPClient_MainLoop (main TCP connection task)"},

        // DataProcess context accessor
        {"4200dbd8", "TCPClient_GetState (get TCP client connection state)"},

        // TCPClient_SetTimer (set heartbeat timer callback)
        {"4200db1a", "TCPClient_SetTimer (set heartbeat timer interval and callback)"},

        // DataProcess_LinkTransport
        {"4200a436", "DataProcess_LinkTransport (link DataProcess to transport context)"},

        // DataProcess_Recv log (packet framing and hex dump)
        {"4200c180", "DataProcess_LogPacket (log/dump packet hex)"},
    };

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String outputDir = args.length > 0 ? args[0] : "/tmp/ghidra_esp32_output";
        new File(outputDir).mkdirs();

        DecompInterface decomp = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        decomp.setOptions(opts);
        decomp.openProgram(currentProgram);

        FunctionManager funcMgr = currentProgram.getFunctionManager();
        AddressSpace space = currentProgram.getAddressFactory().getDefaultAddressSpace();

        String path = outputDir + "/decompiled_missing.c";
        int count = 0;

        try (PrintWriter pw = new PrintWriter(new FileWriter(path))) {
            pw.println("// Decompilation of missing receive-side protocol functions");
            pw.println("// Generated by Ghidra headless analysis (supplemental)");
            pw.println();

            for (String[] target : TARGETS) {
                String addrStr = target[0];
                String desc = target[1];
                Address addr = space.getAddress(Long.parseUnsignedLong(addrStr, 16));

                Function func = funcMgr.getFunctionAt(addr);
                if (func == null) {
                    func = funcMgr.getFunctionContaining(addr);
                }

                if (func == null) {
                    pw.printf("// === 0x%s: %s === (function not found)%n%n", addrStr, desc);
                    println("WARNING: No function at 0x" + addrStr + " (" + desc + ")");
                    continue;
                }

                DecompileResults result = decomp.decompileFunction(func, 60, monitor);
                if (result != null && result.getDecompiledFunction() != null) {
                    String code = result.getDecompiledFunction().getC();
                    if (code != null) {
                        pw.printf("// === 0x%s: %s ===%n", addrStr, desc);
                        pw.printf("// Function: %s @ %s (%d bytes)%n%n",
                            func.getName(), func.getEntryPoint(),
                            func.getBody().getNumAddresses());
                        pw.println(code);
                        pw.println("=".repeat(80));
                        pw.println();
                        count++;
                        println("OK: " + desc + " (" + func.getBody().getNumAddresses() + " bytes)");
                    }
                } else {
                    pw.printf("// === 0x%s: %s === (decompilation failed)%n%n", addrStr, desc);
                    println("FAIL: " + desc);
                }
            }

            pw.printf("%n// Total: %d/%d functions decompiled%n", count, TARGETS.length);
        }

        println("\nOutput: " + path);
        println("Decompiled " + count + "/" + TARGETS.length + " functions");
    }
}
