"""Constants for the EG4 Web Monitor integration.

This package provides all constants used throughout the integration.
During the refactoring transition, constants are re-exported from
_const_legacy.py for backward compatibility.

Submodules (to be populated during refactoring):
- brand: Brand configuration (BrandConfig, BRAND_*, DOMAIN, etc.)
- config_keys: Configuration keys (CONF_*, defaults, limits)
- modbus: Modbus register addresses and bit fields
- device_types: Device types and inverter families
- limits: Number entity min/max limits
- working_modes: Working mode configurations
- diagnostics: Diagnostic constants and scaling factors
- sensors/: Sensor type definitions
  - types: SensorConfig TypedDict
  - inverter: Main SENSOR_TYPES dictionary
  - mappings: Field mappings and sensor lists
  - gridboss: GridBOSS sensor definitions
  - station: Station/plant sensor definitions
"""

from __future__ import annotations

# Brand configuration - extracted to brand.py
from .brand import (
    BrandConfig,
    BRAND_EG4,
    BRAND_FORTRESS,
    BRAND_LUXPOWER,
    BRAND_NAME,
    CURRENT_BRAND,
    DEFAULT_BASE_URL,
    DEFAULT_UPDATE_INTERVAL,
    DEFAULT_VERIFY_SSL,
    DOMAIN,
    ENTITY_PREFIX,
    MANUFACTURER,
)

# Configuration keys - extracted to config_keys.py
from .config_keys import (
    # Configuration keys
    CONF_BASE_URL,
    CONF_CONNECTION_TYPE,
    CONF_DONGLE_HOST,
    CONF_DONGLE_PORT,
    CONF_DONGLE_SERIAL,
    CONF_DST_SYNC,
    CONF_HYBRID_LOCAL_TYPE,
    CONF_INVERTER_FAMILY,
    CONF_INVERTER_MODEL,
    CONF_INVERTER_SERIAL,
    CONF_LIBRARY_DEBUG,
    CONF_LOCAL_TRANSPORTS,
    CONF_MODBUS_HOST,
    CONF_MODBUS_PORT,
    CONF_MODBUS_UNIT_ID,
    CONF_PARAMETER_REFRESH_INTERVAL,
    CONF_PLANT_ID,
    CONF_PLANT_NAME,
    CONF_SENSOR_UPDATE_INTERVAL,
    CONF_VERIFY_SSL,
    # Connection types
    CONNECTION_TYPE_DONGLE,
    CONNECTION_TYPE_HTTP,
    CONNECTION_TYPE_HYBRID,
    CONNECTION_TYPE_LOCAL,
    CONNECTION_TYPE_MODBUS,
    # Hybrid local types
    HYBRID_LOCAL_DONGLE,
    HYBRID_LOCAL_MODBUS,
    HYBRID_LOCAL_NONE,
    # Default values
    DEFAULT_DONGLE_PORT,
    DEFAULT_DONGLE_TIMEOUT,
    DEFAULT_INVERTER_FAMILY,
    DEFAULT_MODBUS_PORT,
    DEFAULT_MODBUS_TIMEOUT,
    DEFAULT_MODBUS_UNIT_ID,
    DEFAULT_PARAMETER_REFRESH_INTERVAL,
    DEFAULT_SENSOR_UPDATE_INTERVAL_HTTP,
    DEFAULT_SENSOR_UPDATE_INTERVAL_LOCAL,
    DONGLE_UPDATE_INTERVAL,
    MAX_PARAMETER_REFRESH_INTERVAL,
    MAX_SENSOR_UPDATE_INTERVAL,
    MIN_PARAMETER_REFRESH_INTERVAL,
    MIN_SENSOR_UPDATE_INTERVAL,
    MODBUS_UPDATE_INTERVAL,
)

# Re-export everything from legacy module for backward compatibility
# As modules are extracted, imports will be updated to pull from submodules
from .._const_legacy import (
    # Classes
    SensorConfig,
    # Modbus registers
    MODBUS_BIT_AC_CHARGE_EN,
    MODBUS_BIT_BAT_SHARED,
    MODBUS_BIT_BATTERY_ECO_EN,
    MODBUS_BIT_BUZZER_EN,
    MODBUS_BIT_CHARGE_LAST,
    MODBUS_BIT_EPS_EN,
    MODBUS_BIT_FORCED_CHG_EN,
    MODBUS_BIT_FORCED_DISCHG_EN,
    MODBUS_BIT_GREEN_EN,
    MODBUS_BIT_MICRO_GRID_EN,
    MODBUS_BIT_PV_GRID_OFF_EN,
    MODBUS_BIT_RUN_WITHOUT_GRID,
    MODBUS_BIT_SET_TO_STANDBY,
    MODBUS_REG_AC_CHARGE_POWER,
    MODBUS_REG_AC_CHARGE_SOC_LIMIT,
    MODBUS_REG_CHARGE_CURRENT,
    MODBUS_REG_CHARGE_POWER_PERCENT,
    MODBUS_REG_DISCHARGE_CURRENT,
    MODBUS_REG_DISCHARGE_POWER_PERCENT,
    MODBUS_REG_FUNC_EN,
    MODBUS_REG_OFFGRID_DISCHG_SOC,
    MODBUS_REG_ONGRID_DISCHG_SOC,
    MODBUS_REG_SYS_FUNC,
    # Device types
    DEVICE_TYPE_BATTERY,
    DEVICE_TYPE_GRIDBOSS,
    DEVICE_TYPE_INVERTER,
    DEVICE_TYPE_STATION,
    # Inverter families
    INVERTER_FAMILY_DEFAULT_MODELS,
    INVERTER_FAMILY_LXP_EU,
    INVERTER_FAMILY_LXP_LV,
    INVERTER_FAMILY_PV_SERIES,
    INVERTER_FAMILY_SNA,
    INVERTER_FAMILY_UNKNOWN,
    # Feature-based sensor sets
    DISCHARGE_RECOVERY_SENSORS,
    SPLIT_PHASE_ONLY_SENSORS,
    THREE_PHASE_ONLY_SENSORS,
    VOLT_WATT_SENSORS,
    # Number entity limits
    AC_CHARGE_POWER_MAX,
    AC_CHARGE_POWER_MIN,
    AC_CHARGE_POWER_STEP,
    BATTERY_CURRENT_MAX,
    BATTERY_CURRENT_MIN,
    BATTERY_CURRENT_STEP,
    GRID_PEAK_SHAVING_POWER_MAX,
    GRID_PEAK_SHAVING_POWER_MIN,
    GRID_PEAK_SHAVING_POWER_STEP,
    PV_CHARGE_POWER_MAX,
    PV_CHARGE_POWER_MIN,
    PV_CHARGE_POWER_STEP,
    SOC_LIMIT_MAX,
    SOC_LIMIT_MIN,
    SOC_LIMIT_STEP,
    SYSTEM_CHARGE_SOC_LIMIT_MAX,
    SYSTEM_CHARGE_SOC_LIMIT_MIN,
    SYSTEM_CHARGE_SOC_LIMIT_STEP,
    # Sensor types
    SENSOR_TYPES,
    STATION_SENSOR_TYPES,
    # Field mappings
    GRIDBOSS_FIELD_MAPPING,
    INVERTER_ENERGY_FIELD_MAPPING,
    INVERTER_RUNTIME_FIELD_MAPPING,
    PARALLEL_GROUP_FIELD_MAPPING,
    # Sensor lists
    CURRENT_SENSORS,
    DIVIDE_BY_10_SENSORS,
    DIVIDE_BY_100_SENSORS,
    GRIDBOSS_ENERGY_SENSORS,
    VOLTAGE_SENSORS,
    # Working modes
    FUNCTION_PARAM_MAPPING,
    SOC_LIMIT_PARAMS,
    WORKING_MODES,
    # Battery constants
    BATTERY_KEY_PREFIX,
    BATTERY_KEY_SEPARATOR,
    BATTERY_KEY_SHORT_PREFIX,
    # Diagnostic keys
    DIAGNOSTIC_BATTERY_SENSOR_KEYS,
    DIAGNOSTIC_DEVICE_SENSOR_KEYS,
    # Supported models
    SUPPORTED_INVERTER_MODELS,
    # Scaling factors
    BATTERY_CURRENT_SCALE_DECIAMPS,
    BATTERY_TEMPERATURE_SCALE_DECIDEGREES,
    BATTERY_VOLTAGE_SCALE_CENTIVOLTS,
    BATTERY_VOLTAGE_SCALE_MILLIVOLTS,
    # Task cleanup
    BACKGROUND_TASK_CLEANUP_TIMEOUT,
)

__all__ = [
    # Classes
    "BrandConfig",
    "SensorConfig",
    # Brand configuration
    "BRAND_EG4",
    "BRAND_FORTRESS",
    "BRAND_LUXPOWER",
    "BRAND_NAME",
    "CURRENT_BRAND",
    "DEFAULT_BASE_URL",
    "DEFAULT_VERIFY_SSL",
    "DOMAIN",
    "ENTITY_PREFIX",
    "MANUFACTURER",
    # Configuration keys
    "CONF_BASE_URL",
    "CONF_CONNECTION_TYPE",
    "CONF_DONGLE_HOST",
    "CONF_DONGLE_PORT",
    "CONF_DONGLE_SERIAL",
    "CONF_DST_SYNC",
    "CONF_HYBRID_LOCAL_TYPE",
    "CONF_INVERTER_FAMILY",
    "CONF_INVERTER_MODEL",
    "CONF_INVERTER_SERIAL",
    "CONF_LIBRARY_DEBUG",
    "CONF_LOCAL_TRANSPORTS",
    "CONF_MODBUS_HOST",
    "CONF_MODBUS_PORT",
    "CONF_MODBUS_UNIT_ID",
    "CONF_PARAMETER_REFRESH_INTERVAL",
    "CONF_PLANT_ID",
    "CONF_PLANT_NAME",
    "CONF_SENSOR_UPDATE_INTERVAL",
    "CONF_VERIFY_SSL",
    # Connection types
    "CONNECTION_TYPE_DONGLE",
    "CONNECTION_TYPE_HTTP",
    "CONNECTION_TYPE_HYBRID",
    "CONNECTION_TYPE_LOCAL",
    "CONNECTION_TYPE_MODBUS",
    # Hybrid local types
    "HYBRID_LOCAL_DONGLE",
    "HYBRID_LOCAL_MODBUS",
    "HYBRID_LOCAL_NONE",
    # Default values
    "DEFAULT_DONGLE_PORT",
    "DEFAULT_DONGLE_TIMEOUT",
    "DEFAULT_INVERTER_FAMILY",
    "DEFAULT_MODBUS_PORT",
    "DEFAULT_MODBUS_TIMEOUT",
    "DEFAULT_MODBUS_UNIT_ID",
    "DEFAULT_PARAMETER_REFRESH_INTERVAL",
    "DEFAULT_SENSOR_UPDATE_INTERVAL_HTTP",
    "DEFAULT_SENSOR_UPDATE_INTERVAL_LOCAL",
    "DEFAULT_UPDATE_INTERVAL",
    "DONGLE_UPDATE_INTERVAL",
    "MAX_PARAMETER_REFRESH_INTERVAL",
    "MAX_SENSOR_UPDATE_INTERVAL",
    "MIN_PARAMETER_REFRESH_INTERVAL",
    "MIN_SENSOR_UPDATE_INTERVAL",
    "MODBUS_UPDATE_INTERVAL",
    # Modbus registers
    "MODBUS_BIT_AC_CHARGE_EN",
    "MODBUS_BIT_BAT_SHARED",
    "MODBUS_BIT_BATTERY_ECO_EN",
    "MODBUS_BIT_BUZZER_EN",
    "MODBUS_BIT_CHARGE_LAST",
    "MODBUS_BIT_EPS_EN",
    "MODBUS_BIT_FORCED_CHG_EN",
    "MODBUS_BIT_FORCED_DISCHG_EN",
    "MODBUS_BIT_GREEN_EN",
    "MODBUS_BIT_MICRO_GRID_EN",
    "MODBUS_BIT_PV_GRID_OFF_EN",
    "MODBUS_BIT_RUN_WITHOUT_GRID",
    "MODBUS_BIT_SET_TO_STANDBY",
    "MODBUS_REG_AC_CHARGE_POWER",
    "MODBUS_REG_AC_CHARGE_SOC_LIMIT",
    "MODBUS_REG_CHARGE_CURRENT",
    "MODBUS_REG_CHARGE_POWER_PERCENT",
    "MODBUS_REG_DISCHARGE_CURRENT",
    "MODBUS_REG_DISCHARGE_POWER_PERCENT",
    "MODBUS_REG_FUNC_EN",
    "MODBUS_REG_OFFGRID_DISCHG_SOC",
    "MODBUS_REG_ONGRID_DISCHG_SOC",
    "MODBUS_REG_SYS_FUNC",
    # Device types
    "DEVICE_TYPE_BATTERY",
    "DEVICE_TYPE_GRIDBOSS",
    "DEVICE_TYPE_INVERTER",
    "DEVICE_TYPE_STATION",
    # Inverter families
    "INVERTER_FAMILY_DEFAULT_MODELS",
    "INVERTER_FAMILY_LXP_EU",
    "INVERTER_FAMILY_LXP_LV",
    "INVERTER_FAMILY_PV_SERIES",
    "INVERTER_FAMILY_SNA",
    "INVERTER_FAMILY_UNKNOWN",
    # Feature-based sensor sets
    "DISCHARGE_RECOVERY_SENSORS",
    "SPLIT_PHASE_ONLY_SENSORS",
    "THREE_PHASE_ONLY_SENSORS",
    "VOLT_WATT_SENSORS",
    # Number entity limits
    "AC_CHARGE_POWER_MAX",
    "AC_CHARGE_POWER_MIN",
    "AC_CHARGE_POWER_STEP",
    "BATTERY_CURRENT_MAX",
    "BATTERY_CURRENT_MIN",
    "BATTERY_CURRENT_STEP",
    "GRID_PEAK_SHAVING_POWER_MAX",
    "GRID_PEAK_SHAVING_POWER_MIN",
    "GRID_PEAK_SHAVING_POWER_STEP",
    "PV_CHARGE_POWER_MAX",
    "PV_CHARGE_POWER_MIN",
    "PV_CHARGE_POWER_STEP",
    "SOC_LIMIT_MAX",
    "SOC_LIMIT_MIN",
    "SOC_LIMIT_STEP",
    "SYSTEM_CHARGE_SOC_LIMIT_MAX",
    "SYSTEM_CHARGE_SOC_LIMIT_MIN",
    "SYSTEM_CHARGE_SOC_LIMIT_STEP",
    # Sensor types
    "SENSOR_TYPES",
    "STATION_SENSOR_TYPES",
    # Field mappings
    "GRIDBOSS_FIELD_MAPPING",
    "INVERTER_ENERGY_FIELD_MAPPING",
    "INVERTER_RUNTIME_FIELD_MAPPING",
    "PARALLEL_GROUP_FIELD_MAPPING",
    # Sensor lists
    "CURRENT_SENSORS",
    "DIVIDE_BY_10_SENSORS",
    "DIVIDE_BY_100_SENSORS",
    "GRIDBOSS_ENERGY_SENSORS",
    "VOLTAGE_SENSORS",
    # Working modes
    "FUNCTION_PARAM_MAPPING",
    "SOC_LIMIT_PARAMS",
    "WORKING_MODES",
    # Battery constants
    "BATTERY_KEY_PREFIX",
    "BATTERY_KEY_SEPARATOR",
    "BATTERY_KEY_SHORT_PREFIX",
    # Diagnostic keys
    "DIAGNOSTIC_BATTERY_SENSOR_KEYS",
    "DIAGNOSTIC_DEVICE_SENSOR_KEYS",
    # Supported models
    "SUPPORTED_INVERTER_MODELS",
    # Scaling factors
    "BATTERY_CURRENT_SCALE_DECIAMPS",
    "BATTERY_TEMPERATURE_SCALE_DECIDEGREES",
    "BATTERY_VOLTAGE_SCALE_CENTIVOLTS",
    "BATTERY_VOLTAGE_SCALE_MILLIVOLTS",
    # Task cleanup
    "BACKGROUND_TASK_CLEANUP_TIMEOUT",
]
