name: Claude Issue Assistant

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  claude_auto_respond:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude')
    steps:
      - name: Respond to Claude mention
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            You are an AI assistant for GitHub issues. Your goal is to help maintainers by triaging issues and ensuring the reporter has provided enough information.
            This repository contains code related to Home Assistant custom components and integrations.
            
            Analyze the following GitHub issue. If the issue is missing key information, such as reproduction steps, expected behavior, or code examples, please post a comment asking for the missing details. Be polite and helpful.
            
            **Issue Title:** ${{ github.event.issue.title }}
            **Issue Body:** ${{ github.event.issue.body }}
            
            **Instructions:**
            - Does the issue contain clear reproduction steps?
            - Does the issue clearly describe the expected vs. actual behavior?
            - Does the issue provide a code sample or link to a repository?
            
            If any of this information is missing, please generate a response that asks for the specific missing information.
            Provide helpful information and guidance to the issue reporter.